Repository 133794m3r/itp298_capstone, pull requests merged in 2021-04, with the labels that each got.

#19 Merge the base actor classes and tests into master closing said issues.
  CMakeLists.txt
  classes/fighters/actor.cpp
  classes/fighters/actor.hxx
  classes/fighters/mob.cpp
  classes/fighters/mob.hxx
  classes/fighters/player.cpp
  classes/fighters/player.hxx
  includes.hxx
  random.h
  tests/actor_test.cpp
Labels: enhancement, help wanted

#24 Fixed the Actor and sub classes so that the Battle menus can work.
  classes/fighters/actor.hxx
  classes/fighters/mob.hxx
  classes/fighters/player.hxx
Labels: bug, enhancement

#25 Item base
  classes/items/itembase.cpp
  classes/items/itembase.hxx
Labels: enhancement

#27 Create a readme finally
  README.md
Labels: documentation, enhancement

#28 Battle system is basically done. Just doesn't do Item rewarding yet.
  classes/fighters/actor.hxx
  classes/fighters/mob.hxx
  classes/fighters/player.hxx
  menus/battle.hxx
  random.h
  terminal.hxx
  tests/battle_demo.cpp
Labels: enhancement

#36 Inventory
  CMakeLists.txt
  classes/battle/loottable.hxx
  classes/fighters/actor.hxx
  classes/fighters/mob.hxx
  classes/fighters/player.hxx
  classes/inventory.hxx
  includes.hxx
  tests/actor_test.cpp
  tests/battle_demo.cpp
  tests/inventory_test.cpp
Labels: enhancement

#37 Speedup builds
  CMakeLists.txt
  classes/containers/inventory.hxx
  tests/inventory_test.cpp
Labels: enhancement

#43 Windows will now compile and work right(for MSVC anyways)
  CMakeLists.txt
  classes/containers/inventory.hxx
  classes/containers/loot_table.hxx
  classes/fighters/player.hxx
  random.h
  terminal.hxx
  tests/inventory_test.cpp
Labels: bug, enhancement

#44 Inventory Menu is done
  CMakeLists.txt
  classes/containers/inventory.hxx
  classes/containers/loot_table.hxx
  classes/containers/shop_inventory.hxx
  classes/fighters/actor.hxx
  classes/fighters/player.hxx
  classes/items/armor.hxx
  classes/items/item_base.cpp
  classes/items/item_base.hxx
  classes/items/potion.hxx
  classes/items/weapon.hxx
  classes/shopkeeper.hxx
  menus/battle.hxx
  menus/inputs.hxx
  menus/inventory_menu.hxx
  menus/menu.hxx
  menus/shop.hxx
  terminal.hxx
  tests/inventory_demo.cpp
  tests/item_test.cpp
  tests/shop_test.cpp
Labels: enhancement
